#ifndef MYRHYTHMGAME6_0_GLOBAL_H
#define MYRHYTHMGAME6_0_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYRHYTHMGAME6_0_LIBRARY)
#   define MYRHYTHMGAME6_0_EXPORT Q_DECL_EXPORT
#else
#   define MYRHYTHMGAME6_0_EXPORT Q_DECL_EXPORT
#endif

#endif // MYRHYTHMGAME6_0_GLOBAL_H
